# Woodpecker CI configuration
# Calls the same build script as GitHub Actions

steps:
  - name: build-latest
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        # Download shared build script (pinned to version)
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.1.0/scripts/build.sh"
        chmod +x scripts/build.sh

        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/transmission-wireguard \
          --containerfile Containerfile \
          --tag latest \
          --tag-version \
          --skip-wip \
          --login --push

  - name: build-pkg
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        # Download shared build script (pinned to version)
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.1.0/scripts/build.sh"
        chmod +x scripts/build.sh

        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/transmission-wireguard \
          --containerfile Containerfile.pkg \
          --base-version 15-quarterly \
          --tag pkg \
          --tag-version \
          --version-suffix "-pkg" \
          --skip-wip \
          --login --push

  - name: build-pkg-latest
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        # Download shared build script (pinned to version)
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.1.0/scripts/build.sh"
        chmod +x scripts/build.sh

        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/transmission-wireguard \
          --containerfile Containerfile.pkg \
          --base-version 15 \
          --tag pkg-latest \
          --tag-version \
          --version-suffix "-pkg-latest" \
          --skip-wip \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: [ "*.md", "docs/**", "LICENSE", ".gitignore" ]
  - event: manual
