# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="transmission-daemon transmission-web wireguard-tools ca_root_nss"
ARG UPSTREAM_URL="https://api.github.com/repos/transmission/transmission/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:9091/transmission/web/"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Transmission with WireGuard" \
      org.opencontainers.image.description="Transmission BitTorrent client with built-in WireGuard VPN support." \
      org.opencontainers.image.source="https://github.com/daemonless/transmission-wireguard" \
      org.opencontainers.image.url="https://transmissionbt.com/" \
      org.opencontainers.image.documentation="https://github.com/transmission/transmission" \
      org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Downloaders" \
      io.daemonless.port="9091" \
      io.daemonless.volumes="/config,/downloads,/watch" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.pkg-source="containerfile" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}" \
      org.freebsd.jail.vnet="required"

# Install transmission, wireguard tools
RUN pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    mkdir -p /app && pkg info transmission-daemon | sed -n 's/.*Version.*: *//p' > /app/version && \
    ln -s /usr/local/share/transmission/public_html /usr/local/share/transmission/web && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Create directories (transmission user/group created by package)
RUN mkdir -p /config /downloads /watch /etc/wireguard && \
    chown -R bsd:bsd /config /downloads /watch

# Copy service definitions and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 9091 51413 51413

# --- Volumes (Injected by Generator) ---
VOLUME /config /downloads /watch