icon: ':simple-wireguard:'
cit:
  mode: shell
build:
  pkg_name: transmission-daemon
  variants:
    - tag: pkg
      containerfile: Containerfile.pkg
      aliases: ["latest"]
      default: true
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
